# Generated by Django 3.1.5 on 2021-05-09 16:33

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('billing_details', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing_details',
            name='address_01',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AddField(
            model_name='billing_details',
            name='address_02',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='billing_details',
            name='email_address',
            field=models.EmailField(default='null', max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='billing_details',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, unique=True),
        ),
    ]
