# Generated by Django 3.1.5 on 2021-05-09 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_details', '0002_auto_20210509_1633'),
    ]

    operations = [
        migrations.AddField(
            model_name='billing_details',
            name='city',
            field=models.CharField(blank=True, choices=[('Mumbai', 'Mumbai'), ('Bangalore', 'Bangalore'), ('Delhi', 'Delhi')], max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='billing_details',
            name='order_notes',
            field=models.TextField(blank=True, default='No Data', null=True),
        ),
        migrations.AddField(
            model_name='billing_details',
            name='payement_method',
            field=models.CharField(choices=[('cod', 'Cash On Delivery'), ('online', 'Pay  Online')], default='No Data', max_length=50),
        ),
        migrations.AddField(
            model_name='billing_details',
            name='postal_code',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='billing_details',
            name='state',
            field=models.CharField(default='No Data', max_length=50),
        ),
        migrations.AddField(
            model_name='billing_details',
            name='total_amt',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='billing_details',
            name='address_01',
            field=models.CharField(default='No Data', max_length=100),
        ),
        migrations.AlterField(
            model_name='billing_details',
            name='email_address',
            field=models.EmailField(default='No Data', max_length=254, unique=True),
        ),
    ]
