# Generated by Django 3.1.5 on 2021-05-09 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing_details', '0003_auto_20210509_1709'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing_details',
            name='postal_code',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='billing_details',
            name='total_amt',
            field=models.IntegerField(default=1),
        ),
    ]
