# Generated by Django 3.1.5 on 2021-05-16 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0004_anonmyous_user_active_status'),
        ('billing_details', '0008_auto_20210515_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='billing_details',
            name='anonmyous_user_id',
            field=models.OneToOneField(blank=True, limit_choices_to={'active_status': '1'}, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user_profiles.anonmyous_user'),
        ),
    ]
