# Generated by Django 3.1.5 on 2021-05-16 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg', models.TextField(max_length=350)),
                ('name', models.CharField(max_length=50)),
                ('email_address', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Contact',
            },
        ),
    ]
