# Generated by Django 3.1.5 on 2021-05-16 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0002_content_pages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='content',
            name='heading',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='content',
            name='subcontent',
            field=models.TextField(blank=True, null=True),
        ),
    ]
