# Generated by Django 3.1.5 on 2021-05-16 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_auto_20210516_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pages',
            name='name',
        ),
        migrations.AddField(
            model_name='pages',
            name='heading',
            field=models.CharField(default='No Data', max_length=10),
        ),
        migrations.AddField(
            model_name='pages',
            name='url',
            field=models.CharField(default='404', max_length=20, unique=True),
        ),
    ]
