# Generated by Django 3.1.5 on 2021-05-16 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0004_auto_20210516_1930'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pages',
            name='heading',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='pages',
            name='url',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
