# Generated by Django 3.1.5 on 2021-05-08 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='anonmyous_user',
            name='user_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
