# Generated by Django 3.1.5 on 2021-05-16 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0003_registration'),
    ]

    operations = [
        migrations.AddField(
            model_name='anonmyous_user',
            name='active_status',
            field=models.BooleanField(default=True),
        ),
    ]
