# Generated by Django 3.1.5 on 2021-02-01 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('cutting_price', models.IntegerField()),
                ('is_featured', models.BooleanField()),
                ('is_discountable', models.BooleanField()),
                ('discount', models.IntegerField(blank=True, null=True)),
                ('product_image', models.ImageField(default='No Image', upload_to='uploads/product')),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('category', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='Products.category')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='Product_Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_image', models.ImageField(default='No Image', upload_to='uploads/product')),
                ('product_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Products.products')),
            ],
        ),
    ]
