# Generated by Django 3.1.5 on 2021-02-01 14:11

from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0002_products_size'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterField(
            model_name='products',
            name='category',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Products.category'),
        ),
        migrations.AlterField(
            model_name='products',
            name='size',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('XS', 'Xtra Small Size'), ('S', 'Small Size'), ('M', 'Medium Size'), ('L', 'Large'), ('XL', 'Xtra Size Size')], max_length=11),
        ),
    ]
