# Generated by Django 3.1.5 on 2021-02-01 15:54

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0003_auto_20210201_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='size',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('XS', 'Xtra Small Size'), ('S', 'Small Size'), ('M', 'Medium Size'), ('L', 'Large'), ('XL', 'Xtra Size Size')], max_length=11, null=True),
        ),
    ]
