# Generated by Django 3.1.5 on 2021-02-19 10:52

import Products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_auto_20210201_1554'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='discount',
            field=models.IntegerField(blank=True, default=0, null=True, validators=[Products.models.discount]),
        ),
        migrations.AlterField(
            model_name='products',
            name='is_discountable',
            field=models.BooleanField(validators=[Products.models.is_discountable]),
        ),
    ]
