# Generated by Django 3.1.5 on 2021-02-19 10:53

import Products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0005_auto_20210219_1052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='discount',
            field=models.IntegerField(blank=True, null=True, validators=[Products.models.discount]),
        ),
    ]
