# Generated by Django 3.1.5 on 2021-02-19 17:43

import Products.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0006_auto_20210219_1053'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon_Management',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_code', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Coupon',
                'verbose_name_plural': 'Coupons',
            },
        ),
        migrations.AlterField(
            model_name='products',
            name='discount',
            field=models.IntegerField(default=0, validators=[Products.models.discount], verbose_name='Discount Percentage'),
        ),
    ]
