# Generated by Django 3.1.5 on 2021-02-19 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0007_auto_20210219_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon_management',
            name='product',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='Products.products'),
        ),
    ]
