# Generated by Django 3.1.5 on 2021-05-07 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0009_order_management'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_management',
            name='size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
