# Generated by Django 3.1.5 on 2021-05-08 14:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_profiles', '0001_initial'),
        ('Products', '0010_auto_20210507_1843'),
    ]

    operations = [
        migrations.AddField(
            model_name='order_management',
            name='anonmyous_user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='user_profiles.anonmyous_user'),
        ),
    ]
