# Generated by Django 3.1.5 on 2021-05-16 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0011_order_management_anonmyous_user_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product_image',
            options={'verbose_name': 'Product Image', 'verbose_name_plural': 'Product Images'},
        ),
    ]
